/** Common UK takeaway pizza names — quick-add suggestions only (no prices). */
export const POPULAR_PIZZA_SUGGESTIONS: readonly string[] = [
  "Margherita Pizza",
  "Chips & Cheese Pizza",
  "Mushroom Pizza",
  "Salami Pizza",
  "Tuna Pizza",
  "Chicken Pizza",
  "Ham Pizza",
  "Pepperoni Pizza",
  "BBQ Pepperoni Pizza",
  "Bolognese Pizza",
  "Margherita with Garlic Base Pizza",
  "Doner Pizza",
  "Prawn Pizza",
  "Tuna & Sweetcorn Pizza",
  "Chicken & Mushroom Pizza",
  "Chicken & Sweetcorn Pizza",
  "BBQ Chicken Pizza",
  "Ham & Mushroom Pizza",
  "Ham & Pineapple Pizza",
  "Mexican Pizza",
  "Hot & Spicy Pizza",
  "Hot Shot Pizza",
  "Hot'N'Smelly Pizza",
  "California Chicken Pizza",
  "Spicy Chicken Pizza",
  "Ham, Pepperoni & Salami Pizza",
  "Ham, Pineapple & Mushroom Pizza",
  "Chicken, Sweetcorn & Pineapple Pizza",
  "Al Capone Pizza",
  "Vegetarian Pizza",
  "Hot Vegetarian Pizza",
  "Kiev Pizza",
  "Cheesey Pizza",
  "Americana Pizza",
  "BBQ Pizza",
  "BBQ Doner Pizza",
  "Seafood Pizza",
  "Tandoori Chicken Pizza",
  "Chicken Tikka Pizza",
  "Pepperoni, Onion & Peppers Pizza",
  "Chicken Supreme Pizza",
  "Meat Feast Pizza",
  "Chicken Feast Pizza",
  "Pollo Delight Pizza",
  "Peppino Special Pizza",
  "Mediterranean Chicken Pizza",
  "Chef's Special Pizza",
  "Pepperoni Supreme Pizza",
  "Doner Supreme Pizza",
  "Create your own pizza",
];

export const POPULAR_PIZZA_QUICK_ADD_BATCH = 3;
