/** Generated by scripts/build-hull-sector-boundaries.mjs — do not edit. */
import type { HullSectorDigit } from "./delivery-pricing";

export const HULL_SECTOR_BOUNDARY_INDEX: Record<string, readonly HullSectorDigit[]> = {
  "HU1": ["1","2","3","4"],
  "HU2": ["0","8","9"],
  "HU3": ["1","2","3","4","5","6"],
  "HU4": ["6","7","9"],
  "HU5": ["1","2","3","4","5","9"],
  "HU6": ["0","7","8","9"],
  "HU7": ["0","3","4","5","6","9"],
  "HU8": ["0","7","8","9"],
  "HU9": ["1","2","3","4","5","9"],
  "HU10": ["6","7","9"],
  "HU11": ["4","5"],
  "HU12": ["0","8","9"],
  "HU13": ["0","3","9"],
  "HU14": ["3","9"],
  "HU15": ["1","2"],
  "HU16": ["4","5","9"],
};

