/** Generated by scripts/generate-hull-sector-geocodes.mjs — do not edit by hand. */
export const HULL_SECTOR_GEOCODES = {
  "source": "postcodes.io",
  "generatedAt": "2026-05-16T20:22:06.812Z",
  "outwards": {
    "HU1": {
      "lat": 53.74282923549488,
      "lng": -0.33799071331058017
    },
    "HU2": {
      "lat": 53.75079081770835,
      "lng": -0.3406927187499999
    },
    "HU3": {
      "lat": 53.74229351527219,
      "lng": -0.36774261620185933
    },
    "HU4": {
      "lat": 53.73634949408986,
      "lng": -0.4038609527186761
    },
    "HU5": {
      "lat": 53.7599923632887,
      "lng": -0.3763330592734225
    },
    "HU6": {
      "lat": 53.78108758636369,
      "lng": -0.3714206242424245
    },
    "HU7": {
      "lat": 53.791478032808435,
      "lng": -0.32974287532808394
    },
    "HU8": {
      "lat": 53.76947173030703,
      "lng": -0.2996129385847797
    },
    "HU9": {
      "lat": 53.75620250470803,
      "lng": -0.2886930781544262
    },
    "HU10": {
      "lat": 53.75144256899816,
      "lng": -0.4421637674858225
    },
    "HU11": {
      "lat": 53.8281748615752,
      "lng": -0.221414019093079
    },
    "HU12": {
      "lat": 53.72478618123391,
      "lng": -0.1283798457583547
    },
    "HU13": {
      "lat": 53.72574280930237,
      "lng": -0.43943613255813946
    },
    "HU14": {
      "lat": 53.72868911618259,
      "lng": -0.5000247593360992
    },
    "HU15": {
      "lat": 53.7476131355685,
      "lng": -0.6180075422740524
    },
    "HU16": {
      "lat": 53.781671739837364,
      "lng": -0.4227940467479676
    }
  },
  "sectors": {
    "HU1": {
      "1": {
        "lat": 53.744063,
        "lng": -0.332801,
        "samplePostcode": "HU1 1AA"
      },
      "2": {
        "lat": 53.744525,
        "lng": -0.333086,
        "samplePostcode": "HU1 2AA"
      },
      "3": {
        "lat": 53.746471,
        "lng": -0.335314,
        "samplePostcode": "HU1 3AA"
      },
      "4": {
        "lat": 53.739329,
        "lng": -0.329198,
        "samplePostcode": "HU1 4BG"
      }
    },
    "HU2": {
      "8": {
        "lat": 53.74812,
        "lng": -0.331746,
        "samplePostcode": "HU2 8AA"
      },
      "9": {
        "lat": 53.749502,
        "lng": -0.345173,
        "samplePostcode": "HU2 9AA"
      }
    },
    "HU3": {
      "1": {
        "lat": 53.749742,
        "lng": -0.351488,
        "samplePostcode": "HU3 1AA"
      },
      "2": {
        "lat": 53.737839,
        "lng": -0.351408,
        "samplePostcode": "HU3 2AA"
      },
      "3": {
        "lat": 53.736561,
        "lng": -0.359145,
        "samplePostcode": "HU3 3AD"
      },
      "4": {
        "lat": 53.73633,
        "lng": -0.358669,
        "samplePostcode": "HU3 4AA"
      },
      "5": {
        "lat": 53.734103,
        "lng": -0.374053,
        "samplePostcode": "HU3 5AA"
      },
      "6": {
        "lat": 53.743473,
        "lng": -0.370294,
        "samplePostcode": "HU3 6AB"
      }
    },
    "HU4": {
      "6": {
        "lat": 53.745521,
        "lng": -0.398876,
        "samplePostcode": "HU4 6AB"
      },
      "7": {
        "lat": 53.736436,
        "lng": -0.399813,
        "samplePostcode": "HU4 7AA"
      }
    },
    "HU5": {
      "1": {
        "lat": 53.757307,
        "lng": -0.348628,
        "samplePostcode": "HU5 1AA"
      },
      "2": {
        "lat": 53.763572,
        "lng": -0.359063,
        "samplePostcode": "HU5 2AA"
      },
      "3": {
        "lat": 53.763322,
        "lng": -0.358527,
        "samplePostcode": "HU5 3AA"
      },
      "4": {
        "lat": 53.770283,
        "lng": -0.386584,
        "samplePostcode": "HU5 4AA"
      },
      "5": {
        "lat": 53.75056,
        "lng": -0.38649,
        "samplePostcode": "HU5 5AA"
      }
    },
    "HU6": {
      "7": {
        "lat": 53.785694,
        "lng": -0.361024,
        "samplePostcode": "HU6 7AA"
      },
      "8": {
        "lat": 53.779022,
        "lng": -0.384731,
        "samplePostcode": "HU6 8AA"
      },
      "9": {
        "lat": 53.784475,
        "lng": -0.389136,
        "samplePostcode": "HU6 9AA"
      }
    },
    "HU7": {
      "3": {
        "lat": 53.803011,
        "lng": -0.3535,
        "samplePostcode": "HU7 3AA"
      },
      "4": {
        "lat": 53.783804,
        "lng": -0.339332,
        "samplePostcode": "HU7 4AA"
      },
      "5": {
        "lat": 53.802233,
        "lng": -0.325833,
        "samplePostcode": "HU7 5AA"
      },
      "6": {
        "lat": 53.782277,
        "lng": -0.3162,
        "samplePostcode": "HU7 6AA"
      },
      "9": {
        "lat": 53.777189,
        "lng": -0.34328,
        "samplePostcode": "HU7 9BS"
      }
    },
    "HU8": {
      "7": {
        "lat": 53.748818,
        "lng": -0.329549,
        "samplePostcode": "HU8 7AB"
      },
      "8": {
        "lat": 53.754709,
        "lng": -0.324583,
        "samplePostcode": "HU8 8AE"
      },
      "9": {
        "lat": 53.763184,
        "lng": -0.297029,
        "samplePostcode": "HU8 9AA"
      }
    },
    "HU9": {
      "1": {
        "lat": 53.744093,
        "lng": -0.326567,
        "samplePostcode": "HU9 1AA"
      },
      "2": {
        "lat": 53.753472,
        "lng": -0.313317,
        "samplePostcode": "HU9 2AA"
      },
      "3": {
        "lat": 53.757816,
        "lng": -0.305817,
        "samplePostcode": "HU9 3AA"
      },
      "4": {
        "lat": 53.768238,
        "lng": -0.282092,
        "samplePostcode": "HU9 4AA"
      },
      "5": {
        "lat": 53.762221,
        "lng": -0.27375,
        "samplePostcode": "HU9 5AA"
      },
      "9": {
        "lat": 53.744093,
        "lng": -0.326567,
        "samplePostcode": "HU9 9ES"
      }
    },
    "HU10": {
      "6": {
        "lat": 53.754482,
        "lng": -0.44111,
        "samplePostcode": "HU10 6AA"
      },
      "7": {
        "lat": 53.755666,
        "lng": -0.446421,
        "samplePostcode": "HU10 7AA"
      },
      "9": {
        "lat": 53.720652,
        "lng": -0.429221,
        "samplePostcode": "HU10 9AB"
      }
    },
    "HU11": {
      "4": {
        "lat": 53.778773,
        "lng": -0.247271,
        "samplePostcode": "HU11 4AA"
      },
      "5": {
        "lat": 53.838137,
        "lng": -0.264613,
        "samplePostcode": "HU11 5AA"
      }
    },
    "HU12": {
      "8": {
        "lat": 53.723887,
        "lng": -0.22362,
        "samplePostcode": "HU12 8AA"
      },
      "9": {
        "lat": 53.765483,
        "lng": -0.117176,
        "samplePostcode": "HU12 9AA"
      }
    },
    "HU13": {
      "3": {
        "lat": 53.720652,
        "lng": -0.429221,
        "samplePostcode": "HU13 3AU"
      },
      "9": {
        "lat": 53.72501,
        "lng": -0.435925,
        "samplePostcode": "HU13 9AA"
      }
    },
    "HU14": {
      "3": {
        "lat": 53.717962,
        "lng": -0.503458,
        "samplePostcode": "HU14 3AA"
      },
      "9": {
        "lat": 53.720652,
        "lng": -0.429221,
        "samplePostcode": "HU14 9AD"
      }
    },
    "HU15": {
      "1": {
        "lat": 53.730884,
        "lng": -0.575263,
        "samplePostcode": "HU15 1AA"
      },
      "2": {
        "lat": 53.772793,
        "lng": -0.601431,
        "samplePostcode": "HU15 2AA"
      }
    },
    "HU16": {
      "4": {
        "lat": 53.779662,
        "lng": -0.414469,
        "samplePostcode": "HU16 4AA"
      },
      "5": {
        "lat": 53.781005,
        "lng": -0.421582,
        "samplePostcode": "HU16 5AA"
      },
      "9": {
        "lat": 53.780544,
        "lng": -0.414572,
        "samplePostcode": "HU16 9AF"
      }
    }
  }
} as const;
