export type EastHullMenuCatalogEntry = { name: string; price: number; description?: string };
export type EastHullMenuCatalogCategory = {
  name: string;
  presetKey?: string | null;
  categoryDescription?: string;
  items: EastHullMenuCatalogEntry[];
};

export const EAST_HULL_PIZZA_MENU_CATALOG: EastHullMenuCatalogCategory[] = [
  {
    name: "NEW!! Waffles",
    items: [
      { name: "Strawberry Belgium Waffle", price: 5.49 },
      { name: "Kinder Bueno Belgium Waffle", price: 5.49 },
      { name: "Kit Kat Belgium Waffle", price: 5.49 },
      { name: "Banana Belgium Waffle", price: 5.49 },
      { name: "Oreo Belgium Waffle", price: 5.49 },
    ],
  },
  {
    name: "POPULAR",
    items: [
      { name: "Offer 7", price: 26.4, description: "Any 10\" Pizza, Chicken Kebab, 1/4lb Cheese Burger & Chips, Any 10\" Garlic Bread, Doner Meat, Chips & Salad, Sauce separate" },
      { name: "Creamy Garlic Mushroom & Chicken Spaghetti", price: 10.99, description: "Elevate your takeaway experience with our new addition. Freshly made to order pasta with fresh mushrooms, garlic, seasoned chicken and fresh cream." },
      { name: "Wrap Meal", price: 13.75, description: "Any wrap, any drink, any cake with chips, salad & sauce" },
      { name: "Meat Calzone", price: 9.35, description: "Chicken, ham, pepperoni, onion and salami" },
      { name: "Mixed Kebab - for 2 People", price: 23.1, description: "Lamb & Chicken shish, kofte kebab, doner meat, fried onion, mushrooms, green peppers, chips and two pitta breads" },
      { name: "BBQ Chicken", price: 9.57 },
      { name: "Bad Girl", price: 24.2, description: "1 x chicken burger, 1 x cheese burger, 5 x onion rings, 5 x chicken nuggets, doner meat, cheesy chips, salad, chilli and garlic tubs." },
      { name: "Pizza Fries Pepperoni", price: 9.9 },
      { name: "Kiev", price: 9.46, description: "Chicken, ham, mushrooms and garlic butter" },
    ],
  },
  {
    name: "PIZZAS",
    categoryDescription: "Pizza bases are made from fresh dough with tomato pizza sauce and mozzarella cheese. Our ham is turkey based, bacon and pepperoni are pork.",
    items: [
      { name: "12\" Christmas Tree Pizza", price: 11 },
      { name: "New! 12\" Ey Up Mush Pizza", price: 12.09, description: "Our all times favourite creamy garlic mushrooms & chicken on a fresh pizza dough topped with melted cheese" },
      { name: "Valentines Pizza", price: 10.45, description: "We'll make any 12\" pizza in the shape of heart!" },
      { name: "Bad Boy", price: 24.2, description: "Any 10\" Pizza, Doner Meat, Cheesy Chips, Salad, 5 Chicken Nuggets, 5 Onion Rings, Sauces, Can of Drink" },
      { name: "Mr Calzone", price: 26.4, description: "2 x 7\" Calzones, 5 x onion rings, 5 x chicken nuggets, doner meat, cheesy chips, salad, chilli and garlic tubs." },
      { name: "Pizza Pie", price: 14.3, description: "New! Pizza Pie is here - baked between two pizza crusts topped with cheese, choose any three toppings. Comes with chilli & garlic sauce, plus can of pepsi." },
      { name: "Pizza Margherita", price: 8.25, description: "Tomato sauce and mozzarella cheese" },
      { name: "12\" Nutella Pizza", price: 7.7 },
      { name: "Funghi", price: 9.35, description: "Tomato sauce, mozzarella cheese and mushrooms" },
      { name: "Chicken", price: 9.35, description: "Tomato sauce, mozzarella cheese and chicken" },
      { name: "Pepperoni", price: 9.35, description: "Tomato sauce, mozzarella cheese and pepperoni" },
      { name: "Salami", price: 9.35, description: "Tomato sauce, mozzarella cheese and salami" },
      { name: "Tuna", price: 9.35, description: "Tomato sauce, mozzarella cheese and tuna" },
      { name: "Hawaiian", price: 9.35, description: "Tomato sauce, mozzarella cheese, ham & pineapple" },
      { name: "Ham & Mushroom", price: 9.35, description: "Tomato sauce, mozzarella cheese, ham and mushrooms" },
      { name: "Chicken & Mushroom", price: 9.35, description: "Tomato sauce, mozzarella cheese, chicken and mushrooms" },
      { name: "Doner", price: 9.35, description: "Tomato sauce, mozzarella cheese & doner meat" },
      { name: "California", price: 9.46, description: "Tomato sauce, mozzarella cheese, ham, mushrooms and pineapple" },
      { name: "Farmhouse", price: 9.46, description: "Tomato sauce, mozzarella cheese, ham, garlic butter and onions" },
      { name: "Jimmy Special", price: 9.46, description: "Pepperoni, mushroom and onion" },
      { name: "4 Cheeses", price: 9.46, description: "Tomato sauce and 4 different cheeses" },
      { name: "Kiev", price: 9.46, description: "Chicken, ham, mushrooms and garlic butter" },
      { name: "Mexican", price: 9.46, description: "Bolognese sauce, onions, fresh tomatoes and jalapenos" },
      { name: "Doner Special", price: 9.46, description: "Doner meat, mushrooms, peppers and onions" },
      { name: "Quatro Stagioni", price: 9.46, description: "Ham, pepperoni, jalapenos, onions and garlic butter" },
      { name: "Vegetarian", price: 9.57, description: "Fresh tomatoes, onion, mushrooms, peppers" },
      { name: "Hot Vegetarian", price: 9.57, description: "Fresh tomatoes, onion, mushrooms, peppers, jalapenos and chilli" },
      { name: "Hot Shot", price: 9.57, description: "Pepperoni, salami, onion, peppers, jalapenos and chilli" },
      { name: "House Special", price: 9.57, description: "Ham, pepperoni, mushroom, onion and pepper" },
      { name: "Chicken Supreme", price: 9.57, description: "Chicken, mushroom, green peppers and garlic butter" },
      { name: "Hot Loward's", price: 10.67, description: "Spicy beef, chicken, jalapenos, onions and garlic butter" },
      { name: "Chicken Feast", price: 9.57, description: "Chicken, fresh tomato, peppers and sweetcorn" },
      { name: "Meat Feast", price: 9.57, description: "Ham, pepperoni, salami, chicken and doner meat" },
      { name: "Bolognese Pizza", price: 9.57 },
      { name: "BBQ Chicken", price: 9.57 },
      { name: "Al Capone", price: 9.57, description: "Ham, mushroom, onion, chilli and garlic" },
      { name: "East Hull Special", price: 9.57, description: "A bit of everything, except sea food" },
      { name: "Bacon Pizza", price: 9.9, description: "Bacon, onion, mushroom and pepperoni" },
      { name: "Bacon Mushroom and Onion", price: 9.9 },
    ],
  },
  {
    name: "Munchie Boxes",
    items: [
      { name: "Mr Calzone", price: 26.4, description: "2 x 7\" Calzones, 5 x onion rings, 5 x chicken nuggets, doner meat, cheesy chips, salad, chilli and garlic tubs." },
      { name: "Bad Girl", price: 24.2, description: "1 x chicken burger, 1 x cheese burger, 5 x onion rings, 5 x chicken nuggets, doner meat, cheesy chips, salad, chilli and garlic tubs." },
      { name: "Bad Boy", price: 24.2, description: "Any 10\" Pizza, Doner Meat, Cheesy Chips, Salad, 5 Chicken Nuggets, 5 Onion Rings, Sauces, Can of Drink" },
    ],
  },
  {
    name: "NEW Salads",
    items: [
      { name: "Chicken Salad", price: 5.5, description: "With your lettuce, peppers, tomatoes, cucumber, red onions, sweetcorn & seasoned chicken" },
      { name: "Chicken & Rice Salad", price: 13.2, description: "Grilled peaces of marinated chicken with basmati rice & salad, for a healthier option with us!" },
      { name: "Tuna Salad", price: 6.6, description: "With peppers, cucumbers, tomatoes, lettuce, red onions & sweetcorn" },
    ],
  },
  {
    name: "NEW Pasta",
    items: [
      { name: "Creamy Garlic Mushroom & Chicken Spaghetti", price: 10.99, description: "Elevate your takeaway experience with our new addition. Freshly made to order pasta with fresh mushrooms, garlic, seasoned chicken and fresh cream." },
    ],
  },
  {
    name: "NEW Pizza Doritos",
    items: [
      { name: "Pizza Doritos", price: 9.9, description: "Nachos with pizza sauce, cheese and a topping of your choice" },
    ],
  },
  {
    name: "Pizza Fries",
    items: [
      { name: "Loaded Chicken Tikka Chips", price: 10, description: "New! Topped with cheese" },
      { name: "Pizza Fries Pepperoni", price: 9.9 },
      { name: "Pizza Fries Mushrooms", price: 9.9 },
      { name: "Pizza Fries BBQ Chicken", price: 9.9 },
      { name: "Pizza Fries Doner", price: 9.9 },
      { name: "Pizza Fries Burger", price: 9.9 },
      { name: "Build Your Own Pizza Fries", price: 8.8, description: "Comes with pizza fries, sauce and cheese then choose your toppings" },
    ],
  },
  {
    name: "CALZONES",
    items: [
      { name: "Kiew Calzone", price: 9.35, description: "Chicken, ham, mushroom and garlic base" },
      { name: "Vegetarian Calzone", price: 9.35, description: "Mushroom, onion, green peppers, pineapple and sweetcorn" },
      { name: "Doner Calzone", price: 9.35, description: "Doner meat and  onion" },
      { name: "Meat Calzone", price: 9.35, description: "Chicken, ham, pepperoni, onion and salami" },
    ],
  },
  {
    name: "GARLIC BREAD",
    items: [
      { name: "Plain Garlic Bread", price: 4.4 },
      { name: "Garlic Bread with Cheese", price: 6.6 },
      { name: "Garlic Bread with Tomato", price: 5.5 },
      { name: "Garlic Bread with Mushrooms", price: 5.5 },
      { name: "Garlic Bread with Cheese and Mushroom", price: 6.6 },
      { name: "Spicy Garlic Bread", price: 5.5, description: "Garlic, tomato and chilli powder" },
      { name: "Special Garlic Bread", price: 7.7, description: "Tomato, cheese and mushroom" },
    ],
  },
  {
    name: "BURGERS",
    items: [
      { name: "Plain Burger", price: 5.5 },
      { name: "Cheese Burger", price: 5.5 },
      { name: "Chicken Burger", price: 6.05 },
      { name: "Bacon Cheeseburger", price: 6.05 },
      { name: "Bacon Cheeseburger & Chips", price: 8.47 },
      { name: "Chicken Escalope Burger", price: 6.05, description: "Juicy escalope chicken burger coated in super crunchy panko breadcrumbs" },
      { name: "King Burger", price: 7.15, description: "Triple burger with cheese" },
      { name: "Special Burger", price: 6.27, description: "Beef burger and doner meat" },
      { name: "Hawaiian Burger", price: 6.05, description: "Burger topped with pineapple" },
      { name: "Garlic Burger", price: 6.05, description: "Burger topped with garlic" },
      { name: "Bolognese Burger", price: 6.05, description: "Burger topped with bolognese" },
      { name: "Mushroom Burger", price: 6.05, description: "Burger topped with mushroom" },
      { name: "Mexican Burger", price: 6.05, description: "Burger topped with spicy chilli and mushroom" },
      { name: "Chilli Burger", price: 6.05, description: "Burger topped with chilli sauce" },
      { name: "Doner burger", price: 6.05, description: "Comes with doner not burger." },
    ],
  },
  {
    name: "KEBABS",
    items: [
      { name: "NEW Tandoori Grilled Chicken Kebab", price: 11 },
      { name: "Mixed Kebab - for 2 People", price: 23.1, description: "Lamb & Chicken shish, kofte kebab, doner meat, fried onion, mushrooms, green peppers, chips and two pitta breads" },
      { name: "Chef'c Special", price: 15.4, description: "Chicken and lamb shish, doner meat" },
      { name: "Mixed Shish", price: 14.3, description: "Lamb and chicken shish cooked on charcoal grill" },
      { name: "Lamb Shish Kebab", price: 15.4, description: "Marinated cubes of lamb cooked on charcoal grill" },
      { name: "Mixed Doner Kebab", price: 12.1, description: "Chicken and doner" },
      { name: "Chicken Shish Kebab", price: 11, description: "Specially prepared cubes of chicken cooked on a charcoal grill" },
      { name: "Spicy Kofte Kebab", price: 10.45, description: "Spicy minced lamb cooked on charcoal grill" },
      { name: "Chicken Doner Meat & Chips", price: 10.45 },
      { name: "Doner Meat & Chips", price: 10.45 },
      { name: "Doner Kebab", price: 9.35, description: "Lamb cooked on a revolving spit. Includes two sauces for free." },
      { name: "Chicken Doner", price: 9.35, description: "Chicken cooked on a revolving spit" },
      { name: "Tray of Doner Meat", price: 8.8 },
      { name: "Doner Meat on Nan Bread", price: 9.35 },
      { name: "Chicken Doner Meat on Nan Bread", price: 9.35 },
      { name: "Chicken Shish on Nan Bread", price: 10.45 },
      { name: "Chicken Shish & Doner Meat on Nan Bread", price: 11.55 },
      { name: "Lamb Shish on Nan Bread", price: 14.3 },
      { name: "Mix Doner on Nan Bread", price: 11.55 },
      { name: "Extra Cheese for Kebabs", price: 2.75 },
    ],
  },
  {
    name: "Wraps",
    items: [
      { name: "Mix Doner Wrap", price: 8.8 },
      { name: "Shish Wrap", price: 9.35 },
      { name: "Chicken Stick Wrap", price: 8.25 },
      { name: "Doner Wrap", price: 8.25 },
      { name: "Chicken Doner Wrap", price: 8.25 },
      { name: "Chicken Shish Wrap", price: 8.8 },
      { name: "Cheesy Chips Wrap", price: 6.6 },
      { name: "Wrap Meal", price: 13.2, description: "Any wrap, any drink, any cake with chips, salad & sauce" },
      { name: "NEW Tuna Salad Wrap", price: 8.25 },
    ],
  },
  {
    name: "Specials",
    items: [
      { name: "Bolognese, Cheese & Chips", price: 7.7 },
      { name: "Bolognese & Chips", price: 5.5 },
      { name: "8 Scampi & Chips", price: 8.8 },
      { name: "10 Chicken Nuggets & Chips", price: 6.6 },
      { name: "6 Chicken Nuggets & Chips", price: 5.5 },
      { name: "Chilli Con Carne & Chips", price: 6.6 },
    ],
  },
  {
    name: "Slush Puppies",
    items: [
      { name: "Strawberry Slushie", price: 2.2, description: "New! Perfect summer drink, ice cool strawberry flavour" },
      { name: "Blueberry Slushie", price: 2.2, description: "New! Perfect summer drink, ice cool raspberry flavour" },
      { name: "Mixed Slushie", price: 2.2, description: "New! Perfect summer drink, ice cool mixed flavour, strawberry & blue raspberry" },
    ],
  },
  {
    name: "Kid's Meal",
    items: [
      { name: "7\" Margherita", price: 4.95 },
      { name: "Kids 5 pcs Chicken Nuggets", price: 4.95 },
      { name: "Kids 7\" Pizza Meal", price: 6.05, description: "Choose any 7\" pizza" },
      { name: "Kid's Cheese Burger", price: 4.95 },
      { name: "Kid's Doner Meat", price: 6.05 },
    ],
  },
  {
    name: "Milkshakes",
    items: [
      { name: "NEW! Nutella Milkshake", price: 5.5 },
      { name: "Banana Milkshake", price: 5.5 },
      { name: "Strawberry Milkshake", price: 5.5 },
      { name: "Kit Kat Milkshake", price: 5.5 },
      { name: "Kinder Bueno Milkshake", price: 5.5 },
      { name: "Ferrero Rocher Milkshake", price: 5.5 },
      { name: "Oreo Milkshake", price: 5.5 },
      { name: "NEW Biscoff Milkshake", price: 5.5 },
    ],
  },
  {
    name: "Omelettes",
    categoryDescription: "All served with chips and salad",
    items: [
      { name: "Spanish Omelette", price: 8.8 },
      { name: "Cheese Omelette", price: 7.15 },
      { name: "Mushroom Omelette", price: 7.15 },
      { name: "Ham Omelette", price: 7.15, description: "Our ham is turkey based." },
      { name: "Chicken Omelette", price: 7.15 },
      { name: "Plain Omelette", price: 6.05 },
    ],
  },
  {
    name: "Special Offers",
    items: [
      { name: "Wrap Meal", price: 14.3, description: "Any wrap, any drink, any cake with chips, salad & sauce" },
      { name: "Offer 1", price: 22, description: "Any 10\" Pizza, Doner Meat & Chips, 1/4lb Cheese Burger & Chips, Any 10\" Garlic Bread, Tub of Chilli, Tub of Garlic Sauce, Side Salad and 2 x Cans of Drink" },
      { name: "Offer 2", price: 25.3, description: "Any 12\" Pizza, Doner Meat & Chips, 1/4lb Cheese Burger & Chips, 2 pcs of Chicken & Chips, Any 10\" Garlic Bread, Bottle of Coke" },
      { name: "Offer 3", price: 26.4, description: "2 Medium Doner Kebabs, 2 x Chips, 2 x 1/4lb Cheese Burger, Any 10\" Pizza, Any 10\" Garlic Bread, Tub of Chilli, Tub of Garlic Sauce, 2 Side Salad" },
      { name: "Offer 4", price: 22, description: "Any 2 x 12\" Pizzas, Any 10\" Garlic Bread, 1 Chips, Tub of Coleslaw, 10 Onion Rings" },
      { name: "Offer 5", price: 18.7, description: "1/4lb Cheese Burger & Chips, 10\" Margherita, Any 10\" Garlic Bread, Tray of Doner Meat" },
      { name: "Offer 6", price: 23.1, description: "Any 3 x 10\" Pizzas, 3 x Chips" },
      { name: "Offer 7", price: 26.4, description: "Any 10\" Pizza, Chicken Kebab, 1/4lb Cheese Burger & Chips, Any 10\" Garlic Bread, Doner Meat, Chips & Salad, Sauce separate" },
      { name: "Offer 8", price: 18.7, description: "Any 2 x 10\" Pizzas, 2 x Chips" },
      { name: "Offer 9", price: 18.15, description: "2 x 1/2lb Cheese or Chicken Burger and Chips, Any 10\" Garlic Bread, 2 x Cans Drink" },
      { name: "Offer 10", price: 16.5, description: "2 x 1/4lb Cheese or Chicken Burger & Chips, Any 10\" Garlic Bread, 2 x Cans Drink" },
      { name: "NEW Offer 11", price: 28.6, description: "Any 2 x 12\" calzones, chilli and garlic each, chips & 2 fudge cakes" },
    ],
  },
  {
    name: "Side Orders",
    items: [
      { name: "Loaded Chicken Tikka Chips", price: 10, description: "New! Topped with cheese" },
      { name: "Creamy Garlic Mushrooms with Chicken", price: 8.8 },
      { name: "Creamy Garlic Mushrooms", price: 7.7 },
      { name: "Chips, salad & Pitta Bread", price: 4.07 },
      { name: "Cheesy & Chips", price: 4.18 },
      { name: "Chips & Pitta Bread", price: 3.85 },
      { name: "Chips & Coleslaw", price: 3.3 },
      { name: "12 Onion Rings", price: 2.75 },
      { name: "Tub of Coleslaw", price: 2.75 },
      { name: "Chips & 1 Sauce", price: 2.86 },
      { name: "Side Salad", price: 2.53 },
      { name: "Chips", price: 2.75 },
      { name: "6 Onion Rings", price: 1.87 },
      { name: "Tub of Garlic Butter", price: 1.65 },
      { name: "Tub of Chilli", price: 1.65 },
      { name: "Tub of Garlic", price: 1.65 },
      { name: "Tub of Mayo", price: 1.65 },
      { name: "Tub of Tomato Sauce", price: 1.65 },
      { name: "Chip Butty", price: 3.85 },
      { name: "Chip Butty & Cheese", price: 5.83 },
    ],
  },
  {
    name: "Desserts",
    items: [
      { name: "Chocolate Fudge Cake", price: 4.95 },
      { name: "Strawberry Cake", price: 4.95 },
      { name: "12\" Nutella Pizza", price: 6.6 },
    ],
  },
  {
    name: "DRINKS",
    items: [
      { name: "Coke Can", price: 1.87 },
      { name: "Diet Coke Can", price: 1.87 },
      { name: "Pepsi Can", price: 1.87 },
      { name: "Pepsi Max Can", price: 1.87 },
      { name: "Dr. Pepper Can", price: 1.87 },
      { name: "Tango Orange Can", price: 1.87 },
      { name: "Tango Apple Can", price: 1.87 },
      { name: "Fanta Orange Can", price: 1.87 },
      { name: "7Up Can", price: 1.87 },
      { name: "Bottle of Coke 1.5L", price: 4.4 },
      { name: "Bottle Diet Coke 1.5L", price: 4.4 },
      { name: "Bottle of Pepsi 1.5L", price: 4.4 },
    ],
  },
];
